### ISSUE TITLE
Question about 0 Padding

### ISSUE THREAD

**Issue by iganggang** [VEWOXIC/FITS#18] opened 2024-11-05 07:43 UTC
Dear author,
I see in your code, that there is a 0 padding operation. 0 padding will decrease the amplitude in the frequency domain. How do you deal with it? 
And I have a question. If I know input data have several components. which neural internet can i use?

**Comment by VEWOXIC** [comment] 2024-11-05 07:59
For the energy loss caused by 0 padding, we implement the energy compensation to scale the amplitude of remaining spectrum to the correct value, see in the #1 . 

I am not sure about what the several components refers to, do you mean different modalities? Also I am not sure about what the neural internet is, do you mean neural network?

**Comment by iganggang** [comment] 2024-11-05 08:05
sorry, it is a neural network. yes, different modes.

**Comment by VEWOXIC** [comment] 2024-11-05 09:07
We just finished a new work TGTSF which paves the way of fusing different modalities. Please see the readme of this repo.

**Comment by VEWOXIC** [comment] 2024-11-08 06:37
If there is no further questions, I will close this issue.

**Closed by VEWOXIC** 2024-11-08 06:37 UTC
